theme: jekyll-theme-minimal
title: New Mexico Supercomputing Challenge 2018–2019
description: Nick Bennett's curricular materials created for the 2018–2019 New Mexico Supercomputing Challenge
show_downloads: true
